name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SFML
      run: sudo apt-get -y install libsfml-dev
    - name: build
      run: g++ main.cpp shapes.cpp -D SFML_STATIC -O3 -o tetrahexyl -lsfml-graphics -lsfml-window -lsfml-system
    - name: tar
      run: tar -cJf tetrahexyl.tar.xz tetrahexyl tetrahexyl_icon.png resources/
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: package
          path: "tetrahexyl.tar.xz"
